version: '3.3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sf_catalogue_php
    ports:
      - "8080:8000"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]
    networks:
      - catalogue_network

networks:
  catalogue_network:
    driver: bridge
